include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    deprecated_member_use: ignore
    use_build_context_synchronously: warning
    curly_braces_in_flow_control_structures: ignore
    unused_import: warning
    todo: ignore
  exclude:
    - "**/*.g.dart"
    - "build/**"
    - android/**

linter:
  rules:
    avoid_print: false
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
